import type { Letter } from "./types";

/**
 * ─────────────────────────────────────────────────────────────────────────────
 *  HIER WOHNT DAS GESCHENK.
 *
 *  Dreizehn Briefe, einer pro Monat, immer am 10., vom 7. Jahrestag
 *  (10.10.2026) bis zum 8. Jahrestag (10.10.2027).
 *
 *  Alles hier darfst du umschreiben — Anrede, Absätze, Dates, alles.
 *  Die App zieht sich Titel, Datum und Freischaltung automatisch daraus.
 *  Wenn du einen Brief änderst, musst du sonst nichts anfassen.
 *
 *  Tipp: Die Absätze sind bewusst kurz gehalten. Streu ruhig eure eigenen
 *  Insider ein — genau die Stellen machen so einen Brief unbezahlbar.
 * ─────────────────────────────────────────────────────────────────────────────
 */

export const PAAR = {
  sie: "Bella",
  er: "Marco",
  kosename: "Marcolino Popolino",
  zusammenSeit: "2019-10-10",
  jubilaeum: "2026-10-10",
} as const;

export const LETTERS: Letter[] = [
  {
    id: 1,
    unlock: "2026-10-10",
    monat: "Oktober 2026",
    stempel: "10 · X · 26",
    titel: "Sieben",
    motto: "Der erste Brief. Der, mit dem alles anfängt.",
    season: "herbst",
    stamp: "herz",
    anrede: "Mein liebster Marcolino Popolino,",
    absaetze: [
      "sieben Jahre. Aufgeschrieben ist das nur eine Zahl mit einem Bauch und einem Strich. Gefühlt sind es tausend Sonntagmorgen, ungefähr vierhundert Diskussionen darüber, was wir essen, und ein einziges, sehr langes Gespräch, das seit 2019 einfach nicht aufhört.",
      "Ich wollte dir dieses Jahr nichts schenken, das man einmal auspackt und dann in eine Schublade legt. Also habe ich dir Zeit geschenkt. Dreizehn Briefe, einen für jeden Monat, bis zum 10. Oktober 2027. In jedem steckt ein Date — von mir für uns geplant, passend zur Jahreszeit.",
      "Es gibt nur eine Regel: immer nur einen. Immer am Zehnten. Der Rest bleibt zu, auch wenn du klickst. (Ich kenne dich, Popolino.)",
      "Sieben Jahre lang habe ich mich in dich verliebt. Lass uns das nächste Jahr benutzen, um uns nochmal richtig zu verabreden.",
    ],
    gruss: "Ich liebe dich, heute mehr als 2019 —",
    signatur: "deine Bella",
    ps: "Ja, du darfst jeden Brief so oft wieder lesen, wie du willst. Nur aufmachen darfst du einen pro Monat.",
    date: {
      titel: "Die goldene Stunde",
      kurz: "Ein Herbstspaziergang, der genau dann anfängt, wenn andere umdrehen.",
      ablauf: [
        "Nachmittags losgehen, so dass ihr eine Stunde vor Sonnenuntergang am schönsten Punkt seid.",
        "Thermoskanne aufmachen, Decke ausbreiten, hinsetzen und nichts tun.",
        "Reihum je eine Erinnerung aus jedem der sieben Jahre erzählen. Eine pro Jahr, keine Wiederholungen.",
        "Im Dunkeln nach Hause laufen und unterwegs zusammen entscheiden, was es zum Abendessen gibt.",
      ],
      brauchtIhr: [
        "Eine Thermoskanne (Chai oder heißer Apfelpunsch)",
        "Eine Decke, die dreckig werden darf",
        "Warme Socken — ja, wirklich",
        "Etwas Süßes für die Manteltasche",
      ],
      dauer: "Ein halber Nachmittag bis in die Dämmerung",
      planB: "Wenn es schüttet: Decke aufs Sofa, Kanne auf den Tisch, und die sieben Erinnerungen erzählt ihr trotzdem. Das Erzählen ist das Date, nicht der Wald.",
      soundtrack: "Etwas mit Klavier und wenig Schlagzeug.",
    },
  },
  {
    id: 2,
    unlock: "2026-11-10",
    monat: "November 2026",
    stempel: "10 · XI · 26",
    titel: "Novemberlicht",
    motto: "Draußen grau. Drinnen wir.",
    season: "herbst",
    stamp: "mond",
    anrede: "Lieber Marcolino,",
    absaetze: [
      "November ist der Monat, in dem Deutschland kollektiv beschließt, dass es keinen Sinn mehr hat. Der Himmel hat die Farbe von altem Spülwasser und es wird schon dunkel, bevor man Feierabend gedacht hat.",
      "Ich mag den November trotzdem, und zwar nur wegen dir. Weil du der Mensch bist, mit dem drinnen bleiben kein Rückzug ist, sondern ein Plan.",
      "Dieser Monat kriegt deshalb kein Date, bei dem man raus muss. Dieser Monat kriegt das Gegenteil.",
    ],
    gruss: "Bis später auf dem Sofa,",
    signatur: "deine Bella",
    date: {
      titel: "Die Höhle",
      kurz: "Ein Kinoabend, bei dem das Bauwerk wichtiger ist als der Film.",
      ablauf: [
        "Erst bauen: Decken, Kissen, Stuhllehnen, Lichterkette. Ohne Bauwerk kein Film.",
        "Karamellpopcorn selbst machen — Zucker in der Pfanne schmelzen, Popcorn rein, schnell schwenken.",
        "Jeder sucht einen Film aus. Zwei Filme, ein Abend. Wer zuerst einschläft, hat verloren.",
        "Handys kommen in eine Schublade in einem anderen Raum.",
      ],
      brauchtIhr: [
        "Alle Decken der Wohnung",
        "Popcornmais, Zucker, Butter, eine Prise Salz",
        "Eine Lichterkette",
        "Zwei Filme: einer von dir, einer von mir",
      ],
      dauer: "Ein ganzer Abend",
      planB: "Zu müde für zwei Filme? Dann einer und dazu die guten Snacks, die man sonst nicht kauft.",
      soundtrack: "Der Vorspann. Mehr braucht es nicht.",
    },
  },
  {
    id: 3,
    unlock: "2026-12-10",
    monat: "Dezember 2026",
    stempel: "10 · XII · 26",
    titel: "Zimt & Lichterketten",
    motto: "Der Monat, in dem alles nach Vanille riecht.",
    season: "winter",
    stamp: "tanne",
    anrede: "Mein liebster Popolino,",
    absaetze: [
      "Ich weiß noch, wie wir das erste Mal zusammen auf einem Weihnachtsmarkt standen. Es war voll, es war zu teuer, mir war kalt an den Füßen — und ich wollte trotzdem nirgendwo anders sein.",
      "Genau das ist glaube ich der ganze Trick an uns: dass die unspektakulären Sachen mit dir irgendwie zählen.",
      "Also machen wir das dieses Jahr wieder. Mit einem Zusatz, damit es nicht nur Wiederholung ist, sondern Tradition.",
    ],
    gruss: "Mit kalten Händen und warmem Herzen,",
    signatur: "deine Bella",
    ps: "Ich sage jetzt schon: die Zimtsterne werden schief. Das gehört dazu.",
    date: {
      titel: "Backen & Budenzauber",
      kurz: "Erst die Küche verwüsten, dann sich draußen aufwärmen.",
      ablauf: [
        "Nachmittags backen: eine Sorte, die wir können, und eine, die wir noch nie gemacht haben.",
        "Die misslungene Sorte wird trotzdem verschenkt. An Nachbarn, Kollegen, wen auch immer.",
        "Abends auf den Weihnachtsmarkt. Jeder gibt zehn Euro aus — aber nur für den anderen.",
        "Eine Tasse teilen statt zwei kaufen. Ist romantischer und wärmer.",
      ],
      brauchtIhr: [
        "Mehl, Butter, Zucker, Mandeln, Zimt",
        "Ausstechformen (oder ein Glas, geht auch)",
        "Zwei mal zehn Euro in bar",
        "Handschuhe. Beide Paare.",
      ],
      dauer: "Nachmittag plus Abend",
      planB: "Weihnachtsmarkt fällt aus oder ist zu voll? Dann Glühwein selbst ansetzen, Lichter aus, nur Kerzen an, und die Plätzchen sind das Abendessen.",
      soundtrack: "Ella Fitzgerald, Christmas. Nicht verhandelbar.",
    },
  },
  {
    id: 4,
    unlock: "2027-01-10",
    monat: "Januar 2027",
    stempel: "10 · I · 27",
    titel: "Kalte Nasen",
    motto: "Ein neues Jahr, das schon in der zweiten Woche gut wird.",
    season: "winter",
    stamp: "schlittschuh",
    anrede: "Lieber Marco,",
    absaetze: [
      "Der Januar hat einen schlechten Ruf, weil alle im Januar beschließen, bessere Menschen zu werden, und dann am 11. wieder aufhören.",
      "Ich habe keine Vorsätze für dich. Ich habe nur eine Verabredung. Die ist einfacher einzuhalten und macht deutlich mehr Spaß.",
      "Und ich habe dieses eine, sehr konkrete Bild im Kopf: du, rote Nase, viel zu großer Schal, und dieses Lachen, das du machst, wenn dir kalt ist und es dir egal ist.",
    ],
    gruss: "Zieh dich warm an,",
    signatur: "deine Bella",
    date: {
      titel: "Eis & Schokolade",
      kurz: "Zwei Stunden draußen frieren, um sich danach richtig aufzuwärmen.",
      ablauf: [
        "Schlittschuhlaufen gehen. Wer sich öfter festhält, zahlt die Schokolade.",
        "Danach: heiße Schokolade, aber die gute — echte Schokolade in warmer Milch schmelzen, nicht aus der Tüte.",
        "Zurück zuhause: heißes Bad oder heiße Dusche, dann sofort in die dicksten Sachen.",
        "Den Rest des Abends nichts vorhaben. Das ist der Punkt.",
      ],
      brauchtIhr: [
        "Handschuhe (Sturzgefahr, ehrlich)",
        "80 % Schokolade, Vollmilch, eine Prise Salz, Zimt",
        "Zwei Paar dicke Socken",
      ],
      dauer: "Nachmittag",
      planB: "Keine Eisbahn in der Nähe? Dann eine Winterwanderung mit Taschenlampen im Dunkeln. Wirkt genauso, kostet nichts.",
      soundtrack: "Stille und Schlittschuhkufen.",
    },
  },
  {
    id: 5,
    unlock: "2027-02-10",
    monat: "Februar 2027",
    stempel: "10 · II · 27",
    titel: "Vier Hände",
    motto: "Etwas machen, das man danach behalten kann.",
    season: "winter",
    stamp: "tasse",
    anrede: "Mein Marcolino Popolino,",
    absaetze: [
      "Im Februar schenkt man sich normalerweise Sachen, die in zwei Wochen welk sind oder aufgegessen. Ich fand die Idee schöner, an einem Nachmittag etwas herzustellen, aus dem wir danach jahrelang trinken.",
      "Ich habe schon einen Verdacht, wie das ausgeht: meins wird ordentlich und langweilig, deins wird chaotisch und irgendwie besser. So wie immer.",
      "Und in zehn Jahren steht das Ding immer noch im Schrank und wir wissen beide sofort, welcher Nachmittag das war.",
    ],
    gruss: "Für die nächsten zehn Jahre Frühstück,",
    signatur: "deine Bella",
    ps: "Du malst mir eine Tasse, ich male dir eine. Blind. Erst am Ende zeigen.",
    date: {
      titel: "Keramik bemalen",
      kurz: "Zwei Tassen, zwei Stunden, und die Regel, dass keiner spickt.",
      ablauf: [
        "Ein Keramikstudio suchen (in fast jeder Stadt gibt es eins) und einen Termin machen.",
        "Jeder nimmt eine Tasse. Du malst meine, ich male deine.",
        "Nicht zeigen, bevor beide fertig sind.",
        "Auf der Unterseite: das Datum. 10.02.2027.",
        "Nach dem Brennen zusammen abholen — das ist quasi ein zweites, kleines Date.",
      ],
      brauchtIhr: [
        "Einen Termin im Keramikstudio",
        "Klamotten, die Farbe abkriegen dürfen",
        "Etwas Geduld für die feinen Pinsel",
      ],
      dauer: "Zwei bis drei Stunden",
      planB: "Kein Studio in der Nähe? Porzellanstifte aus dem Bastelladen, zwei weiße Tassen, im Backofen fixieren. Funktioniert wirklich.",
      soundtrack: "Was im Studio läuft. Man hat da keine Wahl.",
    },
  },
  {
    id: 6,
    unlock: "2027-03-10",
    monat: "März 2027",
    stempel: "10 · III · 27",
    titel: "Etwas, das wächst",
    motto: "Der erste Monat, in dem es wieder nach draußen riecht.",
    season: "fruehling",
    stamp: "tulpe",
    anrede: "Lieber Marcolino,",
    absaetze: [
      "Es gibt diesen einen Tag im März, an dem man morgens rausgeht und die Luft plötzlich anders riecht. Nicht warm, nur anders. Als hätte jemand ein Fenster aufgemacht.",
      "Ich mag den Tag sehr, weil er nach Anfang riecht, und weil wir zwei ja irgendwie gut in Anfängen sind.",
      "Deshalb gibt es diesen Monat ein Date, aus dem etwas übrig bleibt, das danach weiterwächst.",
    ],
    gruss: "Auf ein neues Grün,",
    signatur: "deine Bella",
    date: {
      titel: "Wurzeln schlagen",
      kurz: "Botanischer Garten am Vormittag, Erde unter den Fingernägeln am Nachmittag.",
      ablauf: [
        "Vormittags in den Botanischen Garten oder ein großes Gewächshaus. Jeder sucht sich eine Lieblingspflanze und muss begründen, warum.",
        "Danach in den Pflanzenladen: eine Pflanze für die Wohnung, gemeinsam ausgesucht — sie muss beiden gefallen.",
        "Zuhause einpflanzen, Namen geben, auf einen Zettel schreiben, wann sie eingezogen ist.",
        "Wenn ihr einen Balkon habt: dazu noch Kräuter. Basilikum stirbt sowieso, das ist normal.",
      ],
      brauchtIhr: [
        "Eintritt für den Botanischen Garten (meist unter 10 €)",
        "Einen Topf, Erde, eine Pflanze",
        "Einen Namen — der Teil ist wichtiger als er klingt",
      ],
      dauer: "Ein ganzer Tag, gemütlich",
      planB: "Regen? Gewächshäuser sind überdacht. Das ist der ganze Witz an Gewächshäusern.",
      soundtrack: "Vogelgezwitscher, notfalls von Spotify.",
    },
  },
  {
    id: 7,
    unlock: "2027-04-10",
    monat: "April 2027",
    stempel: "10 · IV · 27",
    titel: "Marcolino Popolino kocht",
    motto: "Der Abend, an dem der Küchenboden bemehlt ist.",
    season: "fruehling",
    stamp: "pasta",
    anrede: "Mein liebster Marcolino Popolino,",
    absaetze: [
      "Es wäre ja fast fahrlässig, dir ein Jahr voller Dates zu schenken und dabei nicht ein einziges Mal auszunutzen, dass du einen Namen hast, der klingt wie eine kleine italienische Stadt.",
      "Also: dieser Monat ist deiner. Wir machen Pasta von Hand. Nicht aufmachen, nicht aufwärmen — von Mehl und Ei an.",
      "Ich warne dich fair: Ich werde die ganze Zeit deinen Namen auf italienisch sagen. Das ist der Preis für die Nudeln.",
    ],
    gruss: "Ti amo, Popolino,",
    signatur: "deine Bella",
    ps: "Die erste Nudel wird zu dick. Die zweite auch. Ab der dritten wird es gut.",
    date: {
      titel: "Pasta da zero",
      kurz: "Ein italienischer Abend, der in der Küche anfängt und dort auch bleibt.",
      ablauf: [
        "Teig: 100 g Mehl und 1 Ei pro Person. Kneten, bis er glatt ist, dann 30 Minuten ruhen lassen.",
        "In der Ruhezeit: Wein aufmachen, Tisch decken, Musik an.",
        "Ausrollen und schneiden. Von Hand geht das mit einem Nudelholz und einem Messer völlig okay.",
        "Sugo dazu: entweder Butter-Salbei (drei Minuten) oder Tomate-Knoblauch (zwanzig).",
        "Am Tisch essen. Nicht vor dem Fernseher. Ein Abend im Jahr geht das.",
      ],
      brauchtIhr: [
        "Mehl (Typ 405 reicht, 00 ist besser), Eier, Salz, Olivenöl",
        "Ein Nudelholz oder eine Weinflasche",
        "Parmesan am Stück, kein geriebener aus der Tüte",
        "Eine Flasche Rotwein",
      ],
      dauer: "Ein ganzer Abend",
      planB: "Keine Kraft für Teig? Dann gute gekaufte Pasta und dafür ein aufwendiges Sugo. Der Abend zählt, nicht die Nudel.",
      soundtrack: "Paolo Conte oder Mina.",
    },
  },
  {
    id: 8,
    unlock: "2027-05-10",
    monat: "Mai 2027",
    stempel: "10 · V · 27",
    titel: "Rückenwind",
    motto: "Raus, und zwar weiter als sonst.",
    season: "fruehling",
    stamp: "fahrrad",
    anrede: "Lieber Marco,",
    absaetze: [
      "Der Mai ist der einzige Monat, in dem in Deutschland wirklich alles gleichzeitig blüht und trotzdem noch niemand über die Hitze klagt. Ein Fenster von ungefähr drei Wochen. Man sollte es benutzen.",
      "Ich will mit dir irgendwo hinfahren, wo wir noch nicht waren. Nicht weit. Nur so weit, dass es sich am Abend nach etwas anfühlt.",
      "Und dann will ich mit dir auf einer Wiese sitzen und nichts Sinnvolles tun.",
    ],
    gruss: "Ich fahr vor,",
    signatur: "deine Bella",
    date: {
      titel: "Bis dahin, wo wir noch nicht waren",
      kurz: "Fahrradtour mit einem Picknick im Gepäck und keinem festen Ziel.",
      ablauf: [
        "Auf der Karte einen Kreis um euch ziehen: alles im Umkreis von 25 km ist erlaubt.",
        "Einen Ort aussuchen, an dem keiner von euch je war. Nach Namen entscheiden ist völlig legitim.",
        "Picknick einpacken und hinfahren. Unterwegs mindestens einmal grundlos anhalten.",
        "Auf einer Wiese essen. Danach eine Stunde nichts tun — das ist ein Programmpunkt, kein Leerlauf.",
      ],
      brauchtIhr: [
        "Zwei Fahrräder und Luft in den Reifen",
        "Brot, Käse, Tomaten, Obst, etwas Kaltes zu trinken",
        "Eine Decke",
        "Sonnencreme (der Mai wird unterschätzt)",
      ],
      dauer: "Ein ganzer Tag",
      planB: "Regen oder platter Reifen: gleiches Picknick, aber im Park um die Ecke. Oder auf dem Wohnzimmerboden, komplett ernst gemeint.",
      soundtrack: "Nur Wind. Kopfhörer bleiben in der Tasche.",
    },
  },
  {
    id: 9,
    unlock: "2027-06-10",
    monat: "Juni 2027",
    stempel: "10 · VI · 27",
    titel: "Die längsten Tage",
    motto: "Wenn es erst um halb elf dunkel wird.",
    season: "sommer",
    stamp: "sonne",
    anrede: "Mein Popolino,",
    absaetze: [
      "Im Juni wird es abends einfach nicht dunkel, und das fühlt sich jedes Jahr an wie ein kleines Geschenk, das man nicht bestellt hat.",
      "Ich habe gemerkt, dass wir die langen Abende meistens verplempern. Man sitzt drin, es ist hell, und irgendwann ist es halt vorbei.",
      "Dieses Jahr nicht. Dieses Jahr nehmen wir uns einen dieser Abende ausdrücklich vor.",
    ],
    gruss: "Bis zum Sonnenuntergang,",
    signatur: "deine Bella",
    date: {
      titel: "Sonnenuntergang, erste Reihe",
      kurz: "Der höchste Punkt in der Nähe, ein Abendessen zum Mitnehmen, und Zeit bis es dunkel ist.",
      ablauf: [
        "Vorher nachschauen, wann die Sonne untergeht. Eine Stunde vorher da sein.",
        "Den höchsten erreichbaren Punkt in eurer Umgebung ansteuern — Hügel, Aussichtsturm, Parkhausdach, Feldweg.",
        "Abendessen mitnehmen statt vorher zu essen. Schmeckt draußen besser.",
        "Bleiben, bis die ersten Sterne da sind. Das dauert länger, als man denkt.",
      ],
      brauchtIhr: [
        "Etwas zu essen zum Mitnehmen",
        "Eine Decke und eine dünne Jacke",
        "Eine Flasche von irgendwas Kaltem",
      ],
      dauer: "Ein langer Abend",
      planB: "Bewölkt? Dann Open-Air-Kino, Autokino oder eine Dachterrasse. Hauptsache draußen und abends.",
      soundtrack: "Das, was du beim Fahren anmachst.",
    },
  },
  {
    id: 10,
    unlock: "2027-07-10",
    monat: "Juli 2027",
    stempel: "10 · VII · 27",
    titel: "Salz auf der Haut",
    motto: "Ein Tag, an dem die Uhr keine Rolle spielt.",
    season: "sommer",
    stamp: "welle",
    anrede: "Lieber Marcolino,",
    absaetze: [
      "Ich glaube, das Beste am Sommer ist nicht die Wärme, sondern dass Zeit im Sommer anders funktioniert. Ein Nachmittag am Wasser dauert gefühlt zwei Tage, und man kann sich hinterher an jede halbe Stunde erinnern.",
      "Genau so einen Tag will ich mit dir. Ohne Programm, ohne Rückfahrt-Uhrzeit, ohne dass wir abends noch was vorhaben.",
      "Nur Wasser, was zu essen, und dieser Zustand, in dem einem alles egal ist außer, wer neben einem liegt.",
    ],
    gruss: "Bis später im Wasser,",
    signatur: "deine Bella",
    date: {
      titel: "Seetag",
      kurz: "Früh los, spät zurück, dazwischen nichts geplant.",
      ablauf: [
        "Früh losfahren, bevor alle anderen dieselbe Idee haben.",
        "Einen Platz suchen und dann nicht mehr wechseln. Der erste Platz ist immer gut genug.",
        "Mindestens einmal reinspringen, auch wenn das Wasser zu kalt ist. Vor allem dann.",
        "Nachmittags Eis. Abends bleiben, bis es kühl wird und man die Handtücher braucht.",
      ],
      brauchtIhr: [
        "Handtücher, Badesachen, Sonnencreme",
        "Wassermelone — schneidet man vorher, klingt banal, ist es nicht",
        "Ein Buch, das man nicht liest",
      ],
      dauer: "Der ganze Tag",
      planB: "Schlechtes Wetter oder kein See in der Nähe? Freibad, Therme, oder ein Fluss. Notfalls: Ventilator, kaltes Getränk, Balkon, dieselbe Playlist.",
      soundtrack: "Irgendwas mit Gitarre und zu viel Hall.",
    },
  },
  {
    id: 11,
    unlock: "2027-08-10",
    monat: "August 2027",
    stempel: "10 · VIII · 27",
    titel: "Sternschnuppen",
    motto: "Zwei Tage nach diesem Brief regnet es Perseiden.",
    season: "sommer",
    stamp: "sternschnuppe",
    anrede: "Mein liebster Marcolino Popolino,",
    absaetze: [
      "Das hier ist der einzige Brief, bei dem ich das Datum wirklich ausgerechnet habe. Jedes Jahr Mitte August fliegt die Erde durch den Staub eines alten Kometen, und in der Nacht vom 12. auf den 13. sieht man am meisten davon.",
      "Du bekommst diesen Brief am 10., damit wir zwei Tage Zeit haben, uns eine dunkle Wiese zu suchen.",
      "Und dann liegen wir da, gucken nach oben, und ich weiß jetzt schon, was ich mir wünsche. Es ist ziemlich genau das, was ich seit sieben Jahren jeden Tag habe.",
    ],
    gruss: "Nicht verraten, sonst geht er nicht in Erfüllung,",
    signatur: "deine Bella",
    ps: "Die beste Zeit ist nach Mitternacht. Wir schlafen am nächsten Tag aus, das ist Teil des Geschenks.",
    date: {
      titel: "Perseiden",
      kurz: "In der Nacht vom 12. auf den 13. August raus, wo keine Straßenlaternen sind.",
      ablauf: [
        "Vorher auf einer Lichtverschmutzungs-Karte einen dunklen Ort in eurer Nähe suchen.",
        "Nach 23 Uhr losfahren. Vorher lohnt es sich kaum.",
        "Zwanzig Minuten liegen, ohne aufs Handy zu gucken — so lange braucht das Auge, um sich anzupassen.",
        "Mitzählen. Wer mehr sieht, darf sich am nächsten Tag das Frühstück wünschen.",
      ],
      brauchtIhr: [
        "Eine Isomatte oder Decke (der Boden ist nachts kalt)",
        "Pullover und lange Hosen, auch im August",
        "Eine Thermoskanne Tee",
        "Rotes Licht statt weißem — Handytaschenlampe mit rotem Papier davor",
      ],
      dauer: "Eine halbe Nacht",
      planB: "Wolken? Dann eine Sternenkarten-App am Fenster und ein Dokumentarfilm über Weltraum, mit Decke. Nächstes Jahr kommen die Perseiden wieder.",
      soundtrack: "Grillen.",
    },
  },
  {
    id: 12,
    unlock: "2027-09-10",
    monat: "September 2027",
    stempel: "10 · IX · 27",
    titel: "Erntedank",
    motto: "Der vorletzte. Langsam wird es wieder Herbst.",
    season: "herbst",
    stamp: "traube",
    anrede: "Lieber Marco,",
    absaetze: [
      "Wir sind fast durch. Noch dieser Brief und dann der letzte, und dann ist ein ganzes Jahr vergangen, seit ich dir dreizehn Umschläge hingelegt habe.",
      "Der September ist mein heimlicher Lieblingsmonat. Noch warm genug für draußen, aber abends schon so, dass man einen Pullover braucht und sich näher setzt.",
      "Deshalb ein Date, bei dem es ums Ernten geht. Passt zum Monat. Und irgendwie auch zu uns gerade.",
    ],
    gruss: "Auf das, was gewachsen ist,",
    signatur: "deine Bella",
    date: {
      titel: "Weinberg & Zwetschgenkuchen",
      kurz: "Ein Nachmittag zwischen Reben, ein Abend mit Blechkuchen.",
      ablauf: [
        "Eine Weinregion in eurer Nähe raussuchen — in Deutschland ist die nächste meist näher als man denkt.",
        "Einen Weinwanderweg gehen. Die sind fast überall ausgeschildert und meistens flach genug zum Reden.",
        "Zwei Flaschen mitnehmen: eine für heute, eine für den 10. Oktober.",
        "Abends Zwetschgenkuchen backen. Hefeteig, Blech, viel zu viele Zwetschgen, Zimtzucker.",
      ],
      brauchtIhr: [
        "Feste Schuhe",
        "Platz im Rucksack für zwei Flaschen",
        "Zwetschgen, Hefe, Mehl, Butter, Zimt",
        "Sahne. Ohne Sahne kein Zwetschgenkuchen.",
      ],
      dauer: "Nachmittag und Abend",
      planB: "Kein Weinberg in Reichweite? Weinhandlung, drei Flaschen, blind verkosten, Zettel und Stift. Überraschend lustig.",
      soundtrack: "Etwas mit Bläsern.",
    },
  },
  {
    id: 13,
    unlock: "2027-10-10",
    monat: "Oktober 2027",
    stempel: "10 · X · 27",
    titel: "Acht",
    motto: "Der letzte Brief. Und gleichzeitig überhaupt nicht.",
    season: "herbst",
    stamp: "blatt",
    anrede: "Mein Marcolino Popolino,",
    absaetze: [
      "Wenn du das liest, sind es acht Jahre. Und ein Jahr, seit ich dir diese Briefe geschenkt habe.",
      "Ich habe sie im Herbst 2026 geschrieben, alle dreizehn an einem Stück, und dabei ziemlich genau gemerkt, wie viel von meinem Leben inzwischen mit deinem verwachsen ist. Ich konnte keinen einzigen Monat planen, ohne dich mitzudenken. Das ist, glaube ich, die eigentliche Nachricht dieses ganzen Geschenks.",
      "Dreizehn Umschläge sind jetzt leer. Wir haben stattdessen dreizehn Nachmittage, die es vorher nicht gab.",
      "Und das Beste: Umschläge kann man neu befüllen.",
    ],
    gruss: "Auf die nächsten acht. Und die acht danach.",
    signatur: "deine Bella",
    ps: "Es gibt tatsächlich noch etwas. Aber nicht auf dieser Website.",
    date: {
      titel: "Von vorn",
      kurz: "Das allererste Date nochmal — so genau wie ihr es noch hinkriegt.",
      ablauf: [
        "Rekonstruiert euer erstes Date. Gleicher Ort, wenn es ihn noch gibt. Sonst der ähnlichste.",
        "Zieht euch an, wie ihr euch damals angezogen hättet. Ja, wirklich.",
        "Bestellt das Gleiche. Wenn keiner sich erinnert: einigt euch auf eine Version und behauptet ab jetzt, es sei so gewesen.",
        "Danach: die Flasche vom September aufmachen und die dreizehn Dates durchgehen. Welches war das beste?",
        "Zum Schluss: jeder schreibt dem anderen einen Brief für nächstes Jahr. Ungeöffnet weglegen bis 10.10.2028.",
      ],
      brauchtIhr: [
        "Die Flasche aus dem September",
        "Zwei Umschläge, zwei Blatt Papier, zwei Stifte",
        "Einen sicheren Ort, an dem man Briefe ein Jahr lang vergisst",
      ],
      dauer: "Ein Abend, der lang wird",
      planB: "Der Ort existiert nicht mehr? Dann geht dahin, wo ihr euch zum ersten Mal gesagt habt, dass es ernst ist. Der zählt genauso.",
      soundtrack: "Euer Lied. Ihr wisst schon, welches.",
    },
  },
];

export function getLetter(id: number): Letter | undefined {
  return LETTERS.find((l) => l.id === id);
}
