import type { Letter } from "./types";

/**
 * ─────────────────────────────────────────────────────────────────────────────
 *  HIER WOHNT DAS GESCHENK.
 *
 *  Dreizehn Briefe, einer pro Monat, immer am 10., vom 7. Jahrestag
 *  (10.10.2026) bis zum 8. Jahrestag (10.10.2027).
 *
 *  Alles hier darfst du umschreiben — Anrede, Absätze, Dates, alles.
 *  Die App zieht sich Titel, Datum und Freischaltung automatisch daraus.
 *  Wenn du einen Brief änderst, musst du sonst nichts anfassen.
 *
 *  Tipp: Die Absätze sind bewusst kurz gehalten. Streu ruhig eure eigenen
 *  Insider ein — genau die Stellen machen so einen Brief unbezahlbar.
 * ─────────────────────────────────────────────────────────────────────────────
 */

export const PAAR = {
  sie: "Bella",
  er: "Marco",
  kosename: "Marcolino Popolino",
  zusammenSeit: "2019-10-10",
  jubilaeum: "2026-10-10",
} as const;

export const LETTERS: Letter[] = [
  {
    id: 1,
    unlock: "2026-10-10",
    monat: "Oktober 2026",
    stempel: "10 · X · 26",
    titel: "Sieben",
    motto: "Der erste Brief. Der, mit dem alles anfängt.",
    season: "herbst",
    stamp: "kino",
    anrede: "Mein liebster Marcolino Popolino,",
    absaetze: [
      "sieben Jahre. Aufgeschrieben ist das nur eine Zahl mit einem Bauch und einem Strich. Gefühlt sind es tausend Sonntagmorgen, ungefähr vierhundert Diskussionen darüber, was wir essen, und ein einziges, sehr langes Gespräch, das seit 2019 einfach nicht aufhört.",
      "Ich wollte dir dieses Jahr nichts schenken, das man einmal auspackt und dann in eine Schublade legt. Also habe ich dir Zeit geschenkt. Dreizehn Briefe, einen für jeden Monat, bis zum 10. Oktober 2027. In jedem steckt ein Date — von mir für uns geplant.",
      "Es gibt nur eine Regel: immer nur einen. Immer am Zehnten. Der Rest bleibt zu, auch wenn du klickst. (Ich kenne dich, Popolino.)",
      "Wir fangen mit etwas an, das wir können: dunkler Saal, zu große Portion Popcorn, du und ich nebeneinander. Sieben Jahre lang habe ich mich in dich verliebt. Lass uns das nächste Jahr benutzen, um uns nochmal richtig zu verabreden.",
    ],
    gruss: "Ich liebe dich, heute mehr als 2019 —",
    signatur: "deine Bella",
    ps: "Ja, du darfst jeden Brief so oft wieder lesen, wie du willst. Nur aufmachen darfst du einen pro Monat.",
    date: {
      titel: "Kino",
      kurz: "Dunkler Saal, viel zu viel Popcorn, du und ich nebeneinander.",
      text: [
        "Wir suchen uns einen Film aus, holen die große Tüte und lassen uns zwei Stunden lang von der Welt in Ruhe. Kein Handy, kein Reden, nur wir und die Leinwand.",
        "Hinterher gehen wir noch irgendwo etwas trinken und zerreden den Film. Das ist fast der schönste Teil.",
      ],
      brauchtIhr: [
        "Zwei Kinokarten",
        "Popcorn — einmal süß, einmal salzig",
        "Zeit danach, der Teil hinterher gehört dazu",
      ],
      dauer: "Ein Abend",
      wetter: "Regen ist hier ausdrücklich willkommen.",
    },
  },
  {
    id: 2,
    unlock: "2026-11-10",
    monat: "November 2026",
    stempel: "10 · XI · 26",
    titel: "Kalte Nasen",
    motto: "Draußen wird es früh dunkel. Umso besser.",
    season: "winter",
    stamp: "schlittschuh",
    anrede: "Lieber Marcolino,",
    absaetze: [
      "November ist der Monat, in dem Deutschland kollektiv beschließt, dass es keinen Sinn mehr hat. Der Himmel hat die Farbe von altem Spülwasser und es wird schon dunkel, bevor man Feierabend gedacht hat.",
      "Ich mag den November trotzdem, und zwar nur wegen dir. Weil du der Mensch bist, mit dem auch ein grauer Nachmittag nach Plan aussieht statt nach Ausharren.",
      "Und ich habe dieses eine, sehr konkrete Bild im Kopf: du, rote Nase, viel zu großer Schal, und dieses Lachen, das du machst, wenn dir kalt ist und es dir egal ist.",
    ],
    gruss: "Zieh dich warm an,",
    signatur: "deine Bella",
    date: {
      titel: "Schlittschuhfahren",
      kurz: "Kalte Nasen, wacklige Knie, und danach heiße Schokolade.",
      text: [
        "Ein paar Runden auf dem Eis, so lange, bis uns die Füße wehtun. Ich halte mich sowieso die ganze Zeit an dir fest, das wissen wir beide.",
        "Danach setzen wir uns irgendwo hin, wärmen uns die Hände an einer Tasse und haben den Rest des Abends nichts mehr vor.",
      ],
      brauchtIhr: [
        "Handschuhe",
        "Dicke Socken",
        "Etwas Geld für die heiße Schokolade danach",
      ],
      dauer: "Ein Nachmittag, der in den Abend läuft",
      wetter: "Je kälter, desto besser. Dann schmeckt die Schokolade hinterher mehr.",
    },
  },
  {
    id: 3,
    unlock: "2026-12-10",
    monat: "Dezember 2026",
    stempel: "10 · XII · 26",
    titel: "Von Bude zu Bude",
    motto: "Der Monat, in dem alles nach Zimt und Lichterketten riecht.",
    season: "winter",
    stamp: "tanne",
    anrede: "Mein liebster Popolino,",
    absaetze: [
      "Weihnachtsmärkte sind eigentlich immer dasselbe: zu voll, zu teuer, und nach zwanzig Minuten sind einem die Füße kalt.",
      "Mit dir mag ich sie trotzdem. Das ist glaube ich der ganze Trick an uns — dass die unspektakulären Sachen zählen, wenn du dabei bist.",
      "Also machen wir das dieses Jahr im großen Stil. Nicht ein Markt, sondern so viele, wie an einen Abend passen.",
    ],
    gruss: "Mit kalten Händen und warmem Herzen,",
    signatur: "deine Bella",
    ps: "Eine Tasse teilen statt zwei kaufen. Ist romantischer und wärmer.",
    date: {
      titel: "Weihnachtsmarkt-Hopping",
      kurz: "Nicht ein Markt, sondern so viele, wie an einen Abend passen.",
      text: [
        "Wir gehen von Markt zu Markt, trinken an jedem etwas anderes und essen uns einmal quer durch. Ohne Plan, ohne Eile.",
        "Irgendwann bleiben wir zwischen den Lichtern stehen, sagen nichts und gucken einfach. Das ist der Moment, für den ich das Ganze mache.",
      ],
      brauchtIhr: [
        "Bargeld für die kleinen Buden",
        "Handschuhe, beide Paare",
        "Dicke Socken — die Füße geben zuerst auf",
      ],
      dauer: "Ein ganzer Abend",
      wetter: "Wenn es schneit, haben wir gewonnen.",
    },
  },
  {
    id: 4,
    unlock: "2027-01-10",
    monat: "Januar 2027",
    stempel: "10 · I · 27",
    titel: "Vier Hände",
    motto: "Etwas machen, das man danach behalten kann.",
    season: "winter",
    stamp: "tasse",
    anrede: "Mein Marcolino Popolino,",
    absaetze: [
      "Der Januar hat einen schlechten Ruf, weil alle im Januar beschließen, bessere Menschen zu werden, und dann am 11. wieder aufhören.",
      "Ich habe keine Vorsätze für dich. Ich habe stattdessen einen Nachmittag, an dem wir etwas herstellen, aus dem wir danach jahrelang trinken.",
      "Ich habe schon einen Verdacht, wie das ausgeht: meins wird ordentlich und langweilig, deins wird chaotisch und irgendwie besser. So wie immer.",
      "Und in zehn Jahren steht das Ding immer noch im Schrank und wir wissen beide sofort, welcher Nachmittag das war.",
    ],
    gruss: "Für die nächsten zehn Jahre Frühstück,",
    signatur: "deine Bella",
    ps: "Du malst mir eine Tasse, ich male dir eine. Blind. Erst am Ende zeigen.",
    date: {
      titel: "Keramik bemalen",
      kurz: "Zwei Tassen, aus denen wir noch in zehn Jahren trinken.",
      text: [
        "Wir setzen uns in ein Keramikstudio und bemalen jeder eine Tasse. Meine wird ordentlich und langweilig, deine wird chaotisch und irgendwie besser. So wie immer.",
        "Ein paar Tage später holen wir sie zusammen ab. Das ist dann quasi ein zweites, kleines Date.",
      ],
      brauchtIhr: [
        "Einen Termin im Keramikstudio",
        "Klamotten, die Farbe abkriegen dürfen",
      ],
      dauer: "Zwei bis drei Stunden",
      wetter: "Ist drinnen — genau richtig für einen ungemütlichen Januartag.",
    },
  },
  {
    id: 5,
    unlock: "2027-02-10",
    monat: "Februar 2027",
    stempel: "10 · II · 27",
    titel: "Ich koche",
    motto: "Du musst diesmal gar nichts. Nur kommen.",
    season: "winter",
    stamp: "pasta",
    anrede: "Mein liebster Marcolino Popolino,",
    absaetze: [
      "Im Februar schenkt man sich normalerweise Sachen, die in zwei Wochen welk sind. Ich fand die Idee schöner, dir einen Abend zu schenken, an dem du wirklich nichts tun musst.",
      "Also: Dieser Monat gehört dir, und ich mache alles. Einkauf, Kochen, Tisch, Abwasch. Du sitzt, trinkst, redest mit mir und schaust zu.",
      "Ich sage dir vorher nicht, was es gibt. Ich sage dir nur, dass es etwas ist, von dem ich weiß, dass du es magst.",
      "Und ich warne dich fair: Ich werde den ganzen Abend deinen Namen auf italienisch sagen. Das ist der Preis für das Essen.",
    ],
    gruss: "Ti amo, Popolino,",
    signatur: "deine Bella",
    ps: "Wirklich: Du darfst nicht abwaschen. Ich meine das ernst.",
    date: {
      titel: "Ich koche für dich",
      kurz: "Du musst nichts. Nur kommen und dich hinsetzen.",
      text: [
        "Ich sage dir eine Uhrzeit, du kommst, und mehr musst du nicht wissen. Ich mache alles — Einkauf, Kochen, Tisch decken, Abwasch.",
        "Deine einzige Aufgabe ist, mit mir zu reden und mir zu sagen, wie es schmeckt. Und wirklich: Du darfst nicht abwaschen.",
      ],
      brauchtIhr: [
        "Einen Abend, an dem wir danach nichts mehr vorhaben",
        "Kerzen und eine Flasche von dem Guten",
      ],
      dauer: "Ein langer Abend",
    },
  },
  {
    id: 6,
    unlock: "2027-03-10",
    monat: "März 2027",
    stempel: "10 · III · 27",
    titel: "Zwei Tassen",
    motto: "Der erste Monat, in dem es wieder nach draußen riecht.",
    season: "fruehling",
    stamp: "kaffee",
    anrede: "Lieber Marcolino,",
    absaetze: [
      "Es gibt diesen einen Tag im März, an dem man morgens rausgeht und die Luft plötzlich anders riecht. Nicht warm, nur anders. Als hätte jemand ein Fenster aufgemacht.",
      "An so einem Tag will ich mit dir Kaffee trinken. Nicht schnell einen zwischendurch, sondern richtig: hinsetzen, Zeit haben, den zweiten bestellen, weil der erste zu schnell weg war.",
      "Wir reden sonst so oft im Vorbeigehen. Diesen Nachmittag reden wir im Sitzen.",
    ],
    gruss: "Auf den zweiten Kaffee,",
    signatur: "deine Bella",
    date: {
      titel: "Kaffee trinken",
      kurz: "Zwei Tassen, viel Zeit, und einfach die Seele baumeln lassen.",
      text: [
        "Wir setzen uns irgendwo hin und trinken Kaffee. Nicht schnell einen zwischendurch, sondern richtig: so lange sitzen bleiben, dass der zweite noch dazukommt.",
        "Wir reden sonst so oft im Vorbeigehen. Diesen Nachmittag reden wir im Sitzen — oder auch mal gar nicht.",
      ],
      brauchtIhr: [
        "Ein Café, in dem man lange sitzen darf",
        "Nichts, was danach ansteht",
      ],
      dauer: "Ein Nachmittag",
      wetter: "Wenn die Sonne rauskommt, draußen. Sonst ans Fenster.",
    },
  },
  {
    id: 7,
    unlock: "2027-04-10",
    monat: "April 2027",
    stempel: "10 · IV · 27",
    titel: "Bergauf, mit Proviant",
    motto: "Raus, und zwar weiter als sonst.",
    season: "fruehling",
    stamp: "berg",
    anrede: "Mein Popolino,",
    absaetze: [
      "Im April riecht es das erste Mal wieder richtig nach draußen, und dann will ich nicht um den Block, sondern weiter weg.",
      "Also dieses Mal von vornherein richtig: eine Wanderung, keine Runde. Mit einem Rucksack, in dem mehr steckt, als wir brauchen.",
      "Das Beste an so einem Tag ist ja nicht der Gipfel. Das Beste ist die Pause auf halber Strecke, wenn man sich hinsetzt und alles schmeckt doppelt so gut.",
    ],
    gruss: "Ich pack den Rucksack,",
    signatur: "deine Bella",
    date: {
      titel: "Wandern mit Snacks",
      kurz: "Eine echte Strecke, und ein Rucksack, der es wert ist.",
      text: [
        "Wir suchen uns eine Tour raus und laufen los. Ich packe den Proviant, und zwar mehr, als wir brauchen.",
        "Das Beste an so einem Tag ist nicht das Ankommen, sondern die Pause auf halber Strecke — wenn man sich hinsetzt und alles doppelt so gut schmeckt.",
      ],
      brauchtIhr: [
        "Feste Schuhe und einen Rucksack",
        "Brot, Käse, Obst, Schokolade",
        "Mehr Wasser, als man denkt",
      ],
      dauer: "Ein ganzer Tag",
      wetter: "Bei Regen ziehen wir Jacken an und gehen trotzdem. Nass wandern ist unterschätzt.",
    },
  },
  {
    id: 8,
    unlock: "2027-05-10",
    monat: "Mai 2027",
    stempel: "10 · V · 27",
    titel: "Decke, Wiese, wir",
    motto: "Das Fenster von drei Wochen, in dem alles blüht.",
    season: "fruehling",
    stamp: "korb",
    anrede: "Lieber Marco,",
    absaetze: [
      "Der Mai ist der einzige Monat, in dem in Deutschland wirklich alles gleichzeitig blüht und trotzdem noch niemand über die Hitze klagt. Ein Fenster von ungefähr drei Wochen. Man sollte es benutzen.",
      "Ich will mit dir auf einer Wiese sitzen und nichts Sinnvolles tun. Das ist die ganze Idee. Kein Programm, keine Uhrzeit, an der wir irgendwo sein müssen.",
      "Wir sind ziemlich gut darin, beschäftigt zu sein. Ich würde gern üben, es mal nicht zu sein.",
    ],
    gruss: "Ich bring die Decke mit,",
    signatur: "deine Bella",
    date: {
      titel: "Picknick",
      kurz: "Eine Decke, eine Wiese, und ausdrücklich kein Plan.",
      text: [
        "Wir suchen uns einen Platz, breiten die Decke aus und legen uns hin. Die Handys bleiben im Korb.",
        "Eine Stunde nichts tun. Das ist der Programmpunkt, nicht der Leerlauf dazwischen.",
      ],
      brauchtIhr: [
        "Eine Decke, die dreckig werden darf",
        "Etwas zu essen und etwas Kaltes zu trinken",
        "Sonnencreme — der Mai wird unterschätzt",
      ],
      dauer: "Ein halber Tag, gemütlich",
      wetter: "Wenn es regnet, breiten wir die Decke im Wohnzimmer aus. Ernst gemeint.",
    },
  },
  {
    id: 9,
    unlock: "2027-06-10",
    monat: "Juni 2027",
    stempel: "10 · VI · 27",
    titel: "Zwei Leinwände",
    motto: "Ein Abend, an dem wir beide etwas anstellen.",
    season: "sommer",
    stamp: "pinsel",
    anrede: "Mein Marcolino Popolino,",
    absaetze: [
      "Wir haben im Januar Tassen bemalt und ich habe gemerkt, wie gern ich dir dabei zusehe, wie du dich konzentrierst. Du machst dann dieses Gesicht. Du weißt schon, welches.",
      "Deshalb nochmal, diesmal ohne Studio und ohne Regeln: ein Abend, zwei Leinwände, Farbe auf dem Tisch.",
      "Es geht ausdrücklich nicht darum, dass es gut wird. Es geht darum, dass wir zwei Stunden nebeneinander sitzen und beide etwas anderes machen als aufs Handy schauen.",
    ],
    gruss: "Zeig nicht her, bevor du fertig bist,",
    signatur: "deine Bella",
    ps: "Aufgabe: Jeder malt eine Erinnerung aus den letzten sieben Jahren. Am Ende muss der andere raten, welche.",
    date: {
      titel: "Malabend",
      kurz: "Zwei Leinwände, viel zu viel Farbe, und niemand, der es bewertet.",
      text: [
        "Wir decken den Tisch mit Zeitungen ab, machen die Farben auf und malen einfach los. Es geht ausdrücklich nicht darum, dass es gut wird.",
        "Zwei Stunden nebeneinander sitzen und beide etwas anderes machen als aufs Handy schauen. Am Ende hängen wir beide Bilder auf, auch das schlechtere.",
      ],
      brauchtIhr: [
        "Zwei Leinwände aus dem Bastelladen",
        "Acrylfarben und ein paar Pinsel",
        "Alte Zeitungen und Klamotten, die Farbe abkriegen dürfen",
      ],
      dauer: "Ein Abend",
      wetter: "Ist drinnen. Draußen darf es ruhig schütten.",
    },
  },
  {
    id: 10,
    unlock: "2027-07-10",
    monat: "Juli 2027",
    stempel: "10 · VII · 27",
    titel: "Kino unter freiem Himmel",
    motto: "Wenn es erst um halb elf dunkel wird.",
    season: "sommer",
    stamp: "mond",
    anrede: "Lieber Marcolino,",
    absaetze: [
      "Wir haben im Oktober mit einem Kinoabend angefangen. Jetzt sind wir zehn Briefe weiter und machen es nochmal — nur ohne Dach.",
      "Im Juli wird es abends einfach nicht dunkel, und das fühlt sich jedes Jahr an wie ein kleines Geschenk, das man nicht bestellt hat. Der Film fängt erst an, wenn die Sonne weg ist. Bis dahin sitzen wir da und warten, und das ist fast der schönste Teil.",
      "Mitbringen: eine Decke, eine Jacke für später, und die Bereitschaft, Mücken zu ignorieren.",
    ],
    gruss: "Bis zum Sonnenuntergang,",
    signatur: "deine Bella",
    date: {
      titel: "Movie Night im Outdoorkino",
      kurz: "Wie im Oktober, nur ohne Dach.",
      text: [
        "Wir kommen früh, suchen uns einen guten Platz und warten, bis es dunkel genug ist. Im Juli dauert das bis halb elf — das Warten gehört dazu.",
        "Eine Decke unter uns, eine über uns, und irgendwann fängt der Film an.",
      ],
      brauchtIhr: [
        "Eine Decke zum Sitzen und eine zum Drüberlegen",
        "Etwas zu essen zum Mitnehmen",
        "Eine dünne Jacke für später",
        "Mückenspray",
      ],
      dauer: "Ein langer Abend",
      wetter: "Bei Regen fällt es aus — dann hängen wir zuhause ein Bettlaken auf.",
    },
  },
  {
    id: 11,
    unlock: "2027-08-10",
    monat: "August 2027",
    stempel: "10 · VIII · 27",
    titel: "Rückenwind",
    motto: "Bis dahin, wo wir noch nicht waren.",
    season: "sommer",
    stamp: "fahrrad",
    anrede: "Mein Popolino,",
    absaetze: [
      "Im April sind wir gelaufen. Diesmal fahren wir, und kommen damit deutlich weiter.",
      "Ich will mit dir irgendwo hinfahren, wo wir noch nie waren. Nicht weit. Nur so weit, dass es sich am Abend nach etwas anfühlt und wir beide müde und zufrieden sind.",
      "Und ich will unterwegs mindestens einmal grundlos anhalten. Nicht weil da etwas ist, sondern weil wir gerade Lust haben.",
    ],
    gruss: "Ich fahr vor,",
    signatur: "deine Bella",
    ps: "Gleiches Foto wie im April, gleiche Pose. Dann haben wir zwei.",
    date: {
      titel: "Radltour mit Snacks",
      kurz: "Weit genug, dass es sich am Abend nach etwas anfühlt.",
      text: [
        "Wir fahren irgendwohin, wo wir noch nie waren. Nicht weit — nur so weit, dass wir abends beide müde und zufrieden sind.",
        "Unterwegs halten wir mindestens einmal grundlos an. Nicht weil da etwas ist, sondern weil wir gerade Lust haben.",
      ],
      brauchtIhr: [
        "Zwei Fahrräder und Luft in den Reifen",
        "Brot, Käse, Obst, etwas Kaltes zu trinken",
        "Sonnencreme",
      ],
      dauer: "Ein ganzer Tag",
      wetter: "Bei Gewitter verschieben wir aufs nächste Wochenende.",
    },
  },
  {
    id: 12,
    unlock: "2027-09-10",
    monat: "September 2027",
    stempel: "10 · IX · 27",
    titel: "Tierpark",
    motto: "Der vorletzte. Ein Tag, an dem wir wieder acht sein dürfen.",
    season: "herbst",
    stamp: "tier",
    anrede: "Lieber Marco,",
    absaetze: [
      "Wir sind fast durch. Noch dieser Brief und dann der letzte, und dann ist ein ganzes Jahr vergangen, seit ich dir dreizehn Umschläge hingelegt habe.",
      "Für den vorletzten wollte ich etwas, bei dem wir beide albern sein dürfen, ohne dass es peinlich ist. Also: Tierpark. Mit allem, was dazugehört — Tiernamen vorlesen, Stimmen für die Tiere erfinden, viel zu lange vor einem Gehege stehen, in dem gerade gar nichts passiert.",
      "Der September ist mein heimlicher Lieblingsmonat. Noch warm genug für draußen, aber abends schon so, dass man einen Pullover braucht und sich näher setzt.",
    ],
    gruss: "Bis vor dem Erdmännchengehege,",
    signatur: "deine Bella",
    date: {
      titel: "Tierpark",
      kurz: "Ein Tag, an dem wir beide wieder acht sein dürfen.",
      text: [
        "Wir gehen früh hin, bevor es voll wird, und lassen uns treiben. Tiernamen vorlesen, Stimmen erfinden, viel zu lange vor einem Gehege stehen, in dem gerade gar nichts passiert.",
        "Und irgendwann ein Eis, egal wie das Wetter ist.",
      ],
      brauchtIhr: [
        "Eintritt und feste Schuhe",
        "Eine Wasserflasche",
        "Einen Pullover für später",
      ],
      dauer: "Ein ganzer Tag",
      wetter: "Bei Regen sind die Tierhäuser offen — und angenehm leer.",
    },
  },
  {
    id: 13,
    unlock: "2027-10-10",
    monat: "Oktober 2027",
    stempel: "10 · X · 27",
    titel: "Acht",
    motto: "Der letzte Brief. Und gleichzeitig überhaupt nicht.",
    season: "herbst",
    stamp: "album",
    anrede: "Mein Marcolino Popolino,",
    absaetze: [
      "Wenn du das liest, sind es acht Jahre. Und ein Jahr, seit ich dir diese Briefe geschenkt habe.",
      "Ich habe sie im Herbst 2026 geschrieben, alle dreizehn an einem Stück, und dabei ziemlich genau gemerkt, wie viel von meinem Leben inzwischen mit deinem verwachsen ist. Ich konnte keinen einzigen Monat planen, ohne dich mitzudenken. Das ist, glaube ich, die eigentliche Nachricht dieses ganzen Geschenks.",
      "Dieses letzte Türchen habe ich absichtlich nicht ausgefüllt. Was wir an diesem Tag machen, legen wir zusammen fest — das erste Date seit einem Jahr, das nicht von mir kommt.",
      "Was ich aber schon geplant habe: Wir machen aus dem Jahr ein Album. Dreizehn Umschläge sind jetzt leer, und wir haben stattdessen dreizehn Nachmittage, die es vorher nicht gab. Die gehören auf Papier.",
      "Und das Beste: Umschläge kann man neu befüllen.",
    ],
    gruss: "Auf die nächsten acht. Und die acht danach.",
    signatur: "I luv u — deine Bella",
    ps: "Es gibt tatsächlich noch etwas. Aber nicht auf dieser Website.",
    date: {
      titel: "Das legen wir zusammen fest",
      kurz: "Das letzte Türchen gehört uns beiden.",
      text: [
        "Was wir an diesem Tag machen, entscheiden wir zusammen. Das erste Date seit einem Jahr, das nicht von mir kommt.",
        "Abends machen wir dann aus dem Jahr ein Album: Fotos einkleben, zu jedem Monat einen Satz dazuschreiben. Was du hier ins Tagebuch getippt hast, kommt mit hinein.",
      ],
      brauchtIhr: [
        "Ein leeres Fotoalbum und Fotokleber",
        "Dreizehn ausgedruckte Fotos, eins pro Monat",
        "Zwei Stifte",
      ],
      dauer: "Ein Tag, der lang wird",
    },
  },
];

export function getLetter(id: number): Letter | undefined {
  return LETTERS.find((l) => l.id === id);
}
