import type { Letter } from "./types";

/**
 * ─────────────────────────────────────────────────────────────────────────────
 *  HIER WOHNT DAS GESCHENK.
 *
 *  Dreizehn Briefe, einer pro Monat, immer am 10., vom 7. Jahrestag
 *  (10.10.2026) bis zum 8. Jahrestag (10.10.2027).
 *
 *  Alles hier darfst du umschreiben — Anrede, Absätze, Dates, alles.
 *  Die App zieht sich Titel, Datum und Freischaltung automatisch daraus.
 *  Wenn du einen Brief änderst, musst du sonst nichts anfassen.
 *
 *  Tipp: Die Absätze sind bewusst kurz gehalten. Streu ruhig eure eigenen
 *  Insider ein — genau die Stellen machen so einen Brief unbezahlbar.
 * ─────────────────────────────────────────────────────────────────────────────
 */

export const PAAR = {
  sie: "Bella",
  er: "Marco",
  kosename: "Marcolino Popolino",
  zusammenSeit: "2019-10-10",
  jubilaeum: "2026-10-10",
} as const;

export const LETTERS: Letter[] = [
  {
    id: 1,
    unlock: "2026-10-10",
    monat: "Oktober 2026",
    stempel: "10 · X · 26",
    titel: "Sieben",
    motto: "Der erste Brief. Der, mit dem alles anfängt.",
    season: "herbst",
    stamp: "kino",
    anrede: "Mein liebster Marcolino Popolino,",
    absaetze: [
      "sieben Jahre. Aufgeschrieben ist das nur eine Zahl mit einem Bauch und einem Strich. Gefühlt sind es tausend Sonntagmorgen, ungefähr vierhundert Diskussionen darüber, was wir essen, und ein einziges, sehr langes Gespräch, das seit 2019 einfach nicht aufhört.",
      "Ich wollte dir dieses Jahr nichts schenken, das man einmal auspackt und dann in eine Schublade legt. Also habe ich dir Zeit geschenkt. Dreizehn Briefe, einen für jeden Monat, bis zum 10. Oktober 2027. In jedem steckt ein Date — von mir für uns geplant.",
      "Es gibt nur eine Regel: immer nur einen. Immer am Zehnten. Der Rest bleibt zu, auch wenn du klickst. (Ich kenne dich, Popolino.)",
      "Wir fangen mit etwas an, das wir können: dunkler Saal, zu große Portion Popcorn, du und ich nebeneinander. Sieben Jahre lang habe ich mich in dich verliebt. Lass uns das nächste Jahr benutzen, um uns nochmal richtig zu verabreden.",
    ],
    gruss: "Ich liebe dich, heute mehr als 2019 —",
    signatur: "deine Bella",
    ps: "Ja, du darfst jeden Brief so oft wieder lesen, wie du willst. Nur aufmachen darfst du einen pro Monat.",
    date: {
      titel: "Erste Reihe",
      kurz: "Ein Kinoabend zum Auftakt — mit der guten Portion Popcorn.",
      ablauf: [
        "Jeder sucht einen Film aus, ohne dem anderen zu verraten, welchen.",
        "Beide Vorschläge aufschreiben, zusammenfalten, ziehen. Der andere kommt beim nächsten Mal dran.",
        "Popcorn: einmal süß, einmal salzig. Nicht diskutieren, einfach beides.",
        "Nach dem Abspann sitzen bleiben, bis das Licht angeht. Danach noch irgendwo etwas trinken und den Film auseinandernehmen.",
      ],
      brauchtIhr: [
        "Zwei Kinokarten",
        "Zwei Zettel und einen Stift für die Filmauswahl",
        "Genug Zeit danach — der Teil hinterher gehört dazu",
      ],
      dauer: "Ein ganzer Abend",
      planB: "Nichts Gutes im Programm? Dann Heimkino: Decken aufs Sofa, Lichterkette an, Karamellpopcorn selbst gemacht — Zucker in der Pfanne schmelzen, Popcorn rein, schnell schwenken.",
      soundtrack: "Der Vorspann. Mehr braucht es nicht.",
    },
  },
  {
    id: 2,
    unlock: "2026-11-10",
    monat: "November 2026",
    stempel: "10 · XI · 26",
    titel: "Kalte Nasen",
    motto: "Draußen wird es früh dunkel. Umso besser.",
    season: "winter",
    stamp: "schlittschuh",
    anrede: "Lieber Marcolino,",
    absaetze: [
      "November ist der Monat, in dem Deutschland kollektiv beschließt, dass es keinen Sinn mehr hat. Der Himmel hat die Farbe von altem Spülwasser und es wird schon dunkel, bevor man Feierabend gedacht hat.",
      "Ich mag den November trotzdem, und zwar nur wegen dir. Weil du der Mensch bist, mit dem auch ein grauer Nachmittag nach Plan aussieht statt nach Ausharren.",
      "Und ich habe dieses eine, sehr konkrete Bild im Kopf: du, rote Nase, viel zu großer Schal, und dieses Lachen, das du machst, wenn dir kalt ist und es dir egal ist.",
    ],
    gruss: "Zieh dich warm an,",
    signatur: "deine Bella",
    date: {
      titel: "Eis & Schokolade",
      kurz: "Zwei Stunden draußen frieren, um sich danach richtig aufzuwärmen.",
      ablauf: [
        "Schlittschuhlaufen gehen. Wer sich öfter festhält, zahlt die heiße Schokolade.",
        "Einmal muss jeder eine Runde ohne Festhalten schaffen. Einmal reicht.",
        "Danach: heiße Schokolade, aber die gute — echte Schokolade in warmer Milch schmelzen, nicht aus der Tüte.",
        "Den Rest des Abends nichts vorhaben. Das ist der Punkt.",
      ],
      brauchtIhr: [
        "Handschuhe (Sturzgefahr, ehrlich)",
        "Dicke Socken, zwei Paar",
        "80 % Schokolade, Vollmilch, eine Prise Salz, Zimt",
      ],
      dauer: "Nachmittag bis in den Abend",
      planB: "Keine Eisbahn offen? Dann eine Winterwanderung mit Taschenlampen im Dunkeln, danach die gleiche heiße Schokolade. Wirkt genauso und kostet nichts.",
      soundtrack: "Stille und Schlittschuhkufen.",
    },
  },
  {
    id: 3,
    unlock: "2026-12-10",
    monat: "Dezember 2026",
    stempel: "10 · XII · 26",
    titel: "Von Bude zu Bude",
    motto: "Der Monat, in dem alles nach Zimt und Lichterketten riecht.",
    season: "winter",
    stamp: "tanne",
    anrede: "Mein liebster Popolino,",
    absaetze: [
      "Ich weiß noch, wie wir das erste Mal zusammen auf einem Weihnachtsmarkt standen. Es war voll, es war zu teuer, mir war kalt an den Füßen — und ich wollte trotzdem nirgendwo anders sein.",
      "Genau das ist glaube ich der ganze Trick an uns: dass die unspektakulären Sachen mit dir irgendwie zählen.",
      "Also machen wir das dieses Jahr im großen Stil. Nicht ein Markt, sondern so viele, wie an einen Abend passen.",
    ],
    gruss: "Mit kalten Händen und warmem Herzen,",
    signatur: "deine Bella",
    ps: "Eine Tasse teilen statt zwei kaufen. Ist romantischer und wärmer.",
    date: {
      titel: "Weihnachtsmarkt-Hopping",
      kurz: "Drei Märkte an einem Abend, und an jedem gibt es etwas anderes.",
      ablauf: [
        "Vorher heraussuchen, welche Märkte in eurer Stadt gleichzeitig offen haben. Drei ist eine gute Zahl.",
        "Regel: An jedem Markt genau eine Sache. Erster Markt trinken, zweiter Markt essen, dritter Markt etwas Süßes.",
        "Jeder gibt zehn Euro aus — aber nur für den anderen. Was, wird nicht vorher abgesprochen.",
        "Am letzten Markt eine Runde stehen bleiben und nichts sagen. Nur gucken.",
      ],
      brauchtIhr: [
        "Zwei mal zehn Euro in bar",
        "Handschuhe. Beide Paare.",
        "Dicke Socken — die Füße geben zuerst auf",
        "Eine Liste mit drei Märkten und wie man zwischen ihnen hinkommt",
      ],
      dauer: "Ein ganzer Abend",
      planB: "Zu kalt, zu voll oder alles abgesagt? Dann Glühwein selbst ansetzen, Lichter aus, nur Kerzen an, und Plätzchen backen — eine Sorte, die wir können, und eine, die wir noch nie gemacht haben.",
      soundtrack: "Ella Fitzgerald, Christmas. Nicht verhandelbar.",
    },
  },
  {
    id: 4,
    unlock: "2027-01-10",
    monat: "Januar 2027",
    stempel: "10 · I · 27",
    titel: "Vier Hände",
    motto: "Etwas machen, das man danach behalten kann.",
    season: "winter",
    stamp: "tasse",
    anrede: "Mein Marcolino Popolino,",
    absaetze: [
      "Der Januar hat einen schlechten Ruf, weil alle im Januar beschließen, bessere Menschen zu werden, und dann am 11. wieder aufhören.",
      "Ich habe keine Vorsätze für dich. Ich habe stattdessen einen Nachmittag, an dem wir etwas herstellen, aus dem wir danach jahrelang trinken.",
      "Ich habe schon einen Verdacht, wie das ausgeht: meins wird ordentlich und langweilig, deins wird chaotisch und irgendwie besser. So wie immer.",
      "Und in zehn Jahren steht das Ding immer noch im Schrank und wir wissen beide sofort, welcher Nachmittag das war.",
    ],
    gruss: "Für die nächsten zehn Jahre Frühstück,",
    signatur: "deine Bella",
    ps: "Du malst mir eine Tasse, ich male dir eine. Blind. Erst am Ende zeigen.",
    date: {
      titel: "Keramik bemalen",
      kurz: "Zwei Tassen, zwei Stunden, und die Regel, dass keiner spickt.",
      ablauf: [
        "Ein Keramikstudio suchen (in fast jeder Stadt gibt es eins) und einen Termin machen.",
        "Jeder nimmt eine Tasse. Du malst meine, ich male deine.",
        "Nicht zeigen, bevor beide fertig sind.",
        "Auf die Unterseite: das Datum. 10.01.2027.",
        "Nach dem Brennen zusammen abholen — das ist quasi ein zweites, kleines Date.",
      ],
      brauchtIhr: [
        "Einen Termin im Keramikstudio",
        "Klamotten, die Farbe abkriegen dürfen",
        "Etwas Geduld für die feinen Pinsel",
      ],
      dauer: "Zwei bis drei Stunden",
      planB: "Kein Studio in der Nähe? Porzellanstifte aus dem Bastelladen, zwei weiße Tassen, im Backofen fixieren. Funktioniert wirklich.",
      soundtrack: "Was im Studio läuft. Man hat da keine Wahl.",
    },
  },
  {
    id: 5,
    unlock: "2027-02-10",
    monat: "Februar 2027",
    stempel: "10 · II · 27",
    titel: "Ich koche",
    motto: "Du musst diesmal gar nichts. Nur kommen.",
    season: "winter",
    stamp: "pasta",
    anrede: "Mein liebster Marcolino Popolino,",
    absaetze: [
      "Im Februar schenkt man sich normalerweise Sachen, die in zwei Wochen welk sind. Ich fand die Idee schöner, dir einen Abend zu schenken, an dem du wirklich nichts tun musst.",
      "Also: Dieser Monat gehört dir, und ich mache alles. Einkauf, Kochen, Tisch, Abwasch. Du sitzt, trinkst, redest mit mir und schaust zu.",
      "Ich sage dir vorher nicht, was es gibt. Ich sage dir nur, dass es etwas ist, von dem ich weiß, dass du es magst.",
      "Und ich warne dich fair: Ich werde den ganzen Abend deinen Namen auf italienisch sagen. Das ist der Preis für das Essen.",
    ],
    gruss: "Ti amo, Popolino,",
    signatur: "deine Bella",
    ps: "Wirklich: Du darfst nicht abwaschen. Ich meine das ernst.",
    date: {
      titel: "Tisch für zwei",
      kurz: "Ich koche, du sitzt. Drei Gänge, ein Abend, keine Diskussion.",
      ablauf: [
        "Ich sage dir eine Uhrzeit. Du kommst, und mehr musst du nicht wissen.",
        "Richtig gedeckter Tisch, Kerzen, das gute Geschirr. Kein Fernseher.",
        "Drei Gänge. Zwischen den Gängen wird nicht aufgestanden, sondern geredet.",
        "Deine einzige Aufgabe: Wein einschenken und mir sagen, wie es schmeckt.",
      ],
      brauchtIhr: [
        "Einen Abend, an dem keiner von uns danach noch etwas vorhat",
        "Kerzen und eine Flasche von dem Guten",
        "Eine Küche, die danach aussehen darf wie ein Schlachtfeld",
      ],
      dauer: "Ein langer Abend",
      planB: "Wenn ich es zeitlich nicht schaffe: dann kochen wir zusammen Pasta von Hand — 100 g Mehl und ein Ei pro Person, kneten, ruhen lassen, ausrollen. Aber der Plan ist, dass du sitzt.",
      soundtrack: "Paolo Conte oder Mina.",
    },
  },
  {
    id: 6,
    unlock: "2027-03-10",
    monat: "März 2027",
    stempel: "10 · III · 27",
    titel: "Zwei Tassen",
    motto: "Der erste Monat, in dem es wieder nach draußen riecht.",
    season: "fruehling",
    stamp: "kaffee",
    anrede: "Lieber Marcolino,",
    absaetze: [
      "Es gibt diesen einen Tag im März, an dem man morgens rausgeht und die Luft plötzlich anders riecht. Nicht warm, nur anders. Als hätte jemand ein Fenster aufgemacht.",
      "An so einem Tag will ich mit dir Kaffee trinken. Nicht schnell einen zwischendurch, sondern richtig: hinsetzen, Zeit haben, den zweiten bestellen, weil der erste zu schnell weg war.",
      "Wir reden sonst so oft im Vorbeigehen. Diesen Nachmittag reden wir im Sitzen.",
    ],
    gruss: "Auf den zweiten Kaffee,",
    signatur: "deine Bella",
    date: {
      titel: "Café-Tour",
      kurz: "Drei Cafés, ein Nachmittag, und in jedem eine andere Frage.",
      ablauf: [
        "Drei Cafés aussuchen, in denen wir noch nie zusammen waren. Kann auch der Bäcker um die Ecke sein.",
        "Erstes Café: Was war das Beste an diesem Winter?",
        "Zweites Café: Was willst du dieses Jahr machen, das wir noch nie gemacht haben?",
        "Drittes Café: Etwas Süßes teilen. Reden ist da optional.",
        "Wer schneller austrinkt, sucht das nächste Café aus.",
      ],
      brauchtIhr: [
        "Drei Adressen, fußläufig auseinander",
        "Bargeld für den kleinen Laden, der keine Karte nimmt",
        "Eine Jacke — März täuscht",
      ],
      dauer: "Ein Nachmittag",
      planB: "Zu ungemütlich draußen? Dann zuhause: guten Kaffee kaufen, zwei Sorten nebeneinander aufbrühen, blind probieren und raten. Die drei Fragen bleiben.",
      soundtrack: "Was auch immer im dritten Café läuft.",
    },
  },
  {
    id: 7,
    unlock: "2027-04-10",
    monat: "April 2027",
    stempel: "10 · IV · 27",
    titel: "Bergauf, mit Proviant",
    motto: "Raus, und zwar weiter als sonst.",
    season: "fruehling",
    stamp: "berg",
    anrede: "Mein Popolino,",
    absaetze: [
      "Du bist derjenige von uns beiden, der bei „lass uns spazieren gehen“ immer die längere Strecke vorschlägt. Ich habe das früher als Zumutung empfunden und inzwischen als eine deiner besten Eigenschaften.",
      "Also dieses Mal von vornherein richtig: eine Wanderung, keine Runde. Mit einem Rucksack, in dem mehr steckt, als wir brauchen.",
      "Das Beste an so einem Tag ist ja nicht der Gipfel. Das Beste ist die Pause auf halber Strecke, wenn man sich hinsetzt und alles schmeckt doppelt so gut.",
    ],
    gruss: "Ich pack den Rucksack,",
    signatur: "deine Bella",
    date: {
      titel: "Wandern mit Snacks",
      kurz: "Eine echte Strecke, und ein Rucksack, der es wert ist.",
      ablauf: [
        "Eine Tour aussuchen, die für uns beide ein bisschen zu lang ist. Nur ein bisschen.",
        "Ich packe den Proviant, du planst den Weg. Keiner redet dem anderen rein.",
        "Auf halber Strecke: große Pause. Hinsetzen, alles auspacken, nichts überspringen.",
        "Oben angekommen ein Foto machen — dasselbe wie beim nächsten Türchen mit Rad, dann haben wir eine Serie.",
      ],
      brauchtIhr: [
        "Feste Schuhe und einen Rucksack",
        "Brot, Käse, hartgekochte Eier, Obst, Schokolade",
        "Deutlich mehr Wasser als man denkt",
        "Pflaster. Immer Pflaster.",
      ],
      dauer: "Ein ganzer Tag",
      planB: "Regen den ganzen Tag? Dann eine kürzere Runde im Wald mit Regenjacke und der gleichen Brotzeit — nass wandern ist unterschätzt. Oder verschieben auf das nächste Wochenende.",
      soundtrack: "Nur Wind. Kopfhörer bleiben in der Tasche.",
    },
  },
  {
    id: 8,
    unlock: "2027-05-10",
    monat: "Mai 2027",
    stempel: "10 · V · 27",
    titel: "Decke, Wiese, wir",
    motto: "Das Fenster von drei Wochen, in dem alles blüht.",
    season: "fruehling",
    stamp: "korb",
    anrede: "Lieber Marco,",
    absaetze: [
      "Der Mai ist der einzige Monat, in dem in Deutschland wirklich alles gleichzeitig blüht und trotzdem noch niemand über die Hitze klagt. Ein Fenster von ungefähr drei Wochen. Man sollte es benutzen.",
      "Ich will mit dir auf einer Wiese sitzen und nichts Sinnvolles tun. Das ist die ganze Idee. Kein Programm, keine Uhrzeit, an der wir irgendwo sein müssen.",
      "Wir sind ziemlich gut darin, beschäftigt zu sein. Ich würde gern üben, es mal nicht zu sein.",
    ],
    gruss: "Ich bring die Decke mit,",
    signatur: "deine Bella",
    date: {
      titel: "Picknick",
      kurz: "Ein Korb, eine Decke, und ausdrücklich kein Plan.",
      ablauf: [
        "Einen Platz aussuchen, an dem wir noch nie waren. Park, Flussufer, Feldrand — egal.",
        "Jeder packt drei Sachen ein, ohne dem anderen zu sagen, welche. Sechs Überraschungen.",
        "Ankommen, ausbreiten, hinlegen. Handys bleiben im Korb.",
        "Eine Stunde nichts tun. Das ist ein Programmpunkt, kein Leerlauf.",
      ],
      brauchtIhr: [
        "Eine Decke, die dreckig werden darf",
        "Je drei geheime Mitbringsel",
        "Etwas Kaltes zu trinken",
        "Sonnencreme — der Mai wird unterschätzt",
      ],
      dauer: "Ein halber Tag, gemütlich",
      planB: "Regen? Gleiches Picknick auf dem Wohnzimmerboden. Decke ausbreiten, Möbel ignorieren, komplett ernst gemeint.",
      soundtrack: "Vogelgezwitscher, notfalls von Spotify.",
    },
  },
  {
    id: 9,
    unlock: "2027-06-10",
    monat: "Juni 2027",
    stempel: "10 · VI · 27",
    titel: "Zwei Leinwände",
    motto: "Ein Abend, an dem wir beide etwas anstellen.",
    season: "sommer",
    stamp: "pinsel",
    anrede: "Mein Marcolino Popolino,",
    absaetze: [
      "Wir haben im Januar Tassen bemalt und ich habe gemerkt, wie gern ich dir dabei zusehe, wie du dich konzentrierst. Du machst dann dieses Gesicht. Du weißt schon, welches.",
      "Deshalb nochmal, diesmal ohne Studio und ohne Regeln: ein Abend, zwei Leinwände, Farbe auf dem Tisch.",
      "Es geht ausdrücklich nicht darum, dass es gut wird. Es geht darum, dass wir zwei Stunden nebeneinander sitzen und beide etwas anderes machen als aufs Handy schauen.",
    ],
    gruss: "Zeig nicht her, bevor du fertig bist,",
    signatur: "deine Bella",
    ps: "Aufgabe: Jeder malt eine Erinnerung aus den letzten sieben Jahren. Am Ende muss der andere raten, welche.",
    date: {
      titel: "Malabend",
      kurz: "Zwei Leinwände, viel zu viel Farbe, und niemand, der es bewertet.",
      ablauf: [
        "Tisch mit alten Zeitungen abdecken. Es wird kleckern.",
        "Jeder bekommt eine Leinwand und dieselben Farben.",
        "Thema: eine Erinnerung aus unseren sieben Jahren. Nicht verraten, welche.",
        "Zwei Stunden malen, dabei etwas trinken, nicht rüberschauen.",
        "Am Ende zeigen und raten. Beide Bilder werden aufgehängt, auch das schlechtere.",
      ],
      brauchtIhr: [
        "Zwei Leinwände (Bastelladen, ein paar Euro)",
        "Acrylfarben und ein paar Pinsel",
        "Alte Zeitungen und Klamotten, die Farbe abkriegen dürfen",
        "Etwas zu trinken",
      ],
      dauer: "Ein Abend",
      planB: "Keine Leinwände zur Hand? Dickes Papier tut es auch. Oder wir malen uns gegenseitig — das wird garantiert schlecht und garantiert lustig.",
      soundtrack: "Eine lange Playlist, die keiner von uns skippen muss.",
    },
  },
  {
    id: 10,
    unlock: "2027-07-10",
    monat: "Juli 2027",
    stempel: "10 · VII · 27",
    titel: "Kino unter freiem Himmel",
    motto: "Wenn es erst um halb elf dunkel wird.",
    season: "sommer",
    stamp: "mond",
    anrede: "Lieber Marcolino,",
    absaetze: [
      "Wir haben im Oktober mit einem Kinoabend angefangen. Jetzt sind wir zehn Briefe weiter und machen es nochmal — nur ohne Dach.",
      "Im Juli wird es abends einfach nicht dunkel, und das fühlt sich jedes Jahr an wie ein kleines Geschenk, das man nicht bestellt hat. Der Film fängt erst an, wenn die Sonne weg ist. Bis dahin sitzen wir da und warten, und das ist fast der schönste Teil.",
      "Mitbringen: eine Decke, eine Jacke für später, und die Bereitschaft, Mücken zu ignorieren.",
    ],
    gruss: "Bis zum Sonnenuntergang,",
    signatur: "deine Bella",
    date: {
      titel: "Open-Air-Kino",
      kurz: "Ein Film unter freiem Himmel, und eine Stunde Warten davor.",
      ablauf: [
        "Vorher nachschauen, wo in eurer Nähe Open-Air-Kino läuft — Innenhöfe, Parks, Autokinos, Freibäder.",
        "Eine Stunde vor Filmbeginn da sein und einen guten Platz nehmen. Das Warten gehört zum Date.",
        "Abendessen mitnehmen statt vorher zu essen. Schmeckt draußen besser.",
        "Nach dem Film noch bleiben, bis die meisten weg sind, und in Ruhe zurücklaufen.",
      ],
      brauchtIhr: [
        "Eine Decke zum Sitzen und eine zum Drüberlegen",
        "Etwas zu essen zum Mitnehmen",
        "Eine dünne Jacke — nach Sonnenuntergang wird es kühl",
        "Mückenspray",
      ],
      dauer: "Ein langer Abend",
      planB: "Kein Open-Air in der Nähe oder Regen angesagt? Dann Beamer oder Laptop auf den Balkon, Bettlaken an die Wand, Decke drunter. Zählt genauso.",
      soundtrack: "Grillen, bis der Film anfängt.",
    },
  },
  {
    id: 11,
    unlock: "2027-08-10",
    monat: "August 2027",
    stempel: "10 · VIII · 27",
    titel: "Rückenwind",
    motto: "Bis dahin, wo wir noch nicht waren.",
    season: "sommer",
    stamp: "fahrrad",
    anrede: "Mein Popolino,",
    absaetze: [
      "Im April sind wir gelaufen. Diesmal fahren wir, und kommen damit deutlich weiter.",
      "Ich will mit dir irgendwo hinfahren, wo wir noch nie waren. Nicht weit. Nur so weit, dass es sich am Abend nach etwas anfühlt und wir beide müde und zufrieden sind.",
      "Und ich will unterwegs mindestens einmal grundlos anhalten. Nicht weil da etwas ist, sondern weil wir gerade Lust haben.",
    ],
    gruss: "Ich fahr vor,",
    signatur: "deine Bella",
    ps: "Gleiches Foto wie im April, gleiche Pose. Dann haben wir zwei.",
    date: {
      titel: "Radltour mit Proviant",
      kurz: "Ein Kreis auf der Karte, ein Ort darin, den keiner von uns kennt.",
      ablauf: [
        "Auf der Karte einen Kreis um uns ziehen: alles im Umkreis von 25 km ist erlaubt.",
        "Einen Ort aussuchen, an dem keiner von uns je war. Nach dem Namen entscheiden ist völlig legitim.",
        "Proviant einpacken und losfahren. Unterwegs mindestens einmal grundlos anhalten.",
        "Am Ziel essen, ausruhen, und erst zurückfahren, wenn es sich richtig anfühlt.",
      ],
      brauchtIhr: [
        "Zwei Fahrräder und Luft in den Reifen",
        "Brot, Käse, Tomaten, Obst, etwas Kaltes zu trinken",
        "Flickzeug — einmal im Leben braucht man es",
        "Sonnencreme",
      ],
      dauer: "Ein ganzer Tag",
      planB: "Platter Reifen oder Dauerregen? Dann dasselbe mit dem Zug: eine Station weiter als sonst, aussteigen, laufen, Proviant auspacken.",
      soundtrack: "Nur Wind. Wieder.",
    },
  },
  {
    id: 12,
    unlock: "2027-09-10",
    monat: "September 2027",
    stempel: "10 · IX · 27",
    titel: "Tierpark",
    motto: "Der vorletzte. Ein Tag, an dem wir wieder acht sein dürfen.",
    season: "herbst",
    stamp: "tier",
    anrede: "Lieber Marco,",
    absaetze: [
      "Wir sind fast durch. Noch dieser Brief und dann der letzte, und dann ist ein ganzes Jahr vergangen, seit ich dir dreizehn Umschläge hingelegt habe.",
      "Für den vorletzten wollte ich etwas, bei dem wir beide albern sein dürfen, ohne dass es peinlich ist. Also: Tierpark. Mit allem, was dazugehört — Tiernamen vorlesen, Stimmen für die Tiere erfinden, viel zu lange vor einem Gehege stehen, in dem gerade gar nichts passiert.",
      "Der September ist mein heimlicher Lieblingsmonat. Noch warm genug für draußen, aber abends schon so, dass man einen Pullover braucht und sich näher setzt.",
    ],
    gruss: "Bis vor dem Erdmännchengehege,",
    signatur: "deine Bella",
    date: {
      titel: "Ein Tag im Tierpark",
      kurz: "Jeder sucht sich ein Lieblingstier — und muss es begründen.",
      ablauf: [
        "Früh hin, bevor es voll wird. Vormittags sind die Tiere wacher.",
        "Jeder sucht sich im Lauf des Tages ein Lieblingstier aus und muss am Ende begründen, warum.",
        "Regel: Bei mindestens einem Gehege bleiben wir zehn Minuten stehen, auch wenn nichts passiert.",
        "Zum Schluss noch ein Eis, egal wie das Wetter ist.",
      ],
      brauchtIhr: [
        "Eintritt und feste Schuhe",
        "Eine Wasserflasche pro Person",
        "Kleingeld für Futterautomaten oder Eis",
        "Einen Pullover für später",
      ],
      dauer: "Ein ganzer Tag",
      planB: "Strömender Regen? Dann Aquarium, Zoo mit Tropenhaus oder Naturkundemuseum. Drinnen zählt auch — nur die Regel mit dem Lieblingstier bleibt.",
      soundtrack: "Erdmännchen.",
    },
  },
  {
    id: 13,
    unlock: "2027-10-10",
    monat: "Oktober 2027",
    stempel: "10 · X · 27",
    titel: "Acht",
    motto: "Der letzte Brief. Und gleichzeitig überhaupt nicht.",
    season: "herbst",
    stamp: "album",
    anrede: "Mein Marcolino Popolino,",
    absaetze: [
      "Wenn du das liest, sind es acht Jahre. Und ein Jahr, seit ich dir diese Briefe geschenkt habe.",
      "Ich habe sie im Herbst 2026 geschrieben, alle dreizehn an einem Stück, und dabei ziemlich genau gemerkt, wie viel von meinem Leben inzwischen mit deinem verwachsen ist. Ich konnte keinen einzigen Monat planen, ohne dich mitzudenken. Das ist, glaube ich, die eigentliche Nachricht dieses ganzen Geschenks.",
      "Dieses letzte Türchen habe ich absichtlich nicht ausgefüllt. Was wir an diesem Tag machen, legen wir zusammen fest — das erste Date seit einem Jahr, das nicht von mir kommt.",
      "Was ich aber schon geplant habe: Wir machen aus dem Jahr ein Album. Dreizehn Umschläge sind jetzt leer, und wir haben stattdessen dreizehn Nachmittage, die es vorher nicht gab. Die gehören auf Papier.",
      "Und das Beste: Umschläge kann man neu befüllen.",
    ],
    gruss: "Auf die nächsten acht. Und die acht danach.",
    signatur: "I luv u — deine Bella",
    ps: "Es gibt tatsächlich noch etwas. Aber nicht auf dieser Website.",
    date: {
      titel: "Das Album",
      kurz: "Ein Jahr auf Papier bringen — und den Tag selbst legen wir zusammen fest.",
      ablauf: [
        "Vorher: Wir suchen aus jedem Monat ein Foto aus und lassen sie ausdrucken. Dreizehn Stück.",
        "Am Tag selbst zuerst das, was wir uns gemeinsam ausgedacht haben. Dieses eine Türchen gehört uns beiden.",
        "Abends dann das Album: Fotos einkleben, zu jedem Monat einen Satz dazuschreiben.",
        "Die Notizen aus dem Tagebuch auf dieser Seite abschreiben — die sind schon da, wir müssen sie nur übertragen.",
        "Zum Schluss: jeder schreibt dem anderen einen Brief für nächstes Jahr. Ungeöffnet weglegen bis 10.10.2028.",
      ],
      brauchtIhr: [
        "Ein leeres Fotoalbum und Fotokleber",
        "Dreizehn ausgedruckte Fotos, eins pro Monat",
        "Zwei Stifte, zwei Umschläge, zwei Blatt Papier",
        "Einen sicheren Ort, an dem man Briefe ein Jahr lang vergisst",
      ],
      dauer: "Ein Tag, der lang wird",
      planB: "Keine Zeit für Ausdrucke? Dann erst das Album leer kaufen und die Fotos nachreichen. Der Abend gehört trotzdem dem Durchgehen — welches Türchen war das beste?",
      soundtrack: "Euer Lied. Ihr wisst schon, welches.",
    },
  },
];

export function getLetter(id: number): Letter | undefined {
  return LETTERS.find((l) => l.id === id);
}
